# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube-ado'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=newPipe_newPipe_3898bd90-9a88-4bfa-962a-1a4bc1693f62
      sonar.projectName=newPipe
- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: CmdLine@2
  inputs:
    script: |
      echo creating an index.html file inside path subfolder
      mkdir -p $(Build.Repository.LocalPath)/path
      cd $(Build.Repository.LocalPath)/path
      echo index.html
      ls -l $(Build.Repository.LocalPath)/path
    workingDirectory: '$(Build.Repository.LocalPath)'
  displayName: 'path to HTML'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Build.Repository.LocalPath)/path'
    pathToSources: '$(Build.Repository.LocalPath)/path/index.html'